# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/LabDAC/LabDAC/LabDAC.srcs/sources_1/ip/Rom_Triangle/Rom_Triangle.xci
# IP: The module: 'Rom_Triangle' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LabDAC/LabDAC/LabDAC.srcs/sources_1/ip/Rom_Triangle/Rom_Triangle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rom_Triangle'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/LabDAC/LabDAC/LabDAC.srcs/sources_1/ip/Rom_Triangle/Rom_Triangle.xci
# IP: The module: 'Rom_Triangle' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LabDAC/LabDAC/LabDAC.srcs/sources_1/ip/Rom_Triangle/Rom_Triangle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rom_Triangle'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
