# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/lab1_1/lab1/lab1.srcs/sources_1/ip/Clk_Division/Clk_Division.xci
# IP: The module: 'Clk_Division' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/lab1_1/lab1/lab1.srcs/sources_1/ip/Clk_Division/Clk_Division_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_Division'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/lab1_1/lab1/lab1.srcs/sources_1/ip/Clk_Division/Clk_Division.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_Division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/lab1_1/lab1/lab1.srcs/sources_1/ip/Clk_Division/Clk_Division_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_Division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/lab1_1/lab1/lab1.srcs/sources_1/ip/Clk_Division/Clk_Division.xci
# IP: The module: 'Clk_Division' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/lab1_1/lab1/lab1.srcs/sources_1/ip/Clk_Division/Clk_Division_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_Division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/lab1_1/lab1/lab1.srcs/sources_1/ip/Clk_Division/Clk_Division.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_Division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/lab1_1/lab1/lab1.srcs/sources_1/ip/Clk_Division/Clk_Division_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_Division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
